
CREATE TABLE IF NOT EXISTS login (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(30) NULL DEFAULT NULL,
  pwd VARCHAR(30) NULL DEFAULT NULL,
  email VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (user_id));

CREATE TABLE IF NOT EXISTS balance (
  id INT(11) NOT NULL AUTO_INCREMENT,
  amount INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id) REFERENCES login(user_id));